### ISSUE TITLE
Mejora en CustomPainter -> travel_navigation_bar

### ISSUE THREAD

**Issue by kenyk7** [brocodev/flutter_projects#5]
Hola, estuve revisando un poco y ví que se podía mejorar el CustomPainter en el archivo travel_navigation_bar para que sea mucho más simple y entendible, dejo la líneas de código y la referencia.

Código nuevo:
```dart
final path = Path()
  ..lineTo(w5 - 80, 0)
  ..cubicTo((w5 - 40), 0, (w5 - 50), h5, w5, h6)
  ..cubicTo((w5 + 50), h5, (w5 + 40), 0, (w5 + 80), 0)
  ..lineTo(w, 0)
  ..lineTo(w, h)
  ..lineTo(0, h);
```
Código actual:
```dart
final path = Path()
  ..lineTo(w5 - 80, 0)
  ..cubicTo((w5 - 40), 0, (w5 - 50), h5, w5 - 3, h6)
  ..lineTo(w5, h)
  ..lineTo(w, h)
  ..lineTo(w, 0)
  ..lineTo(w5 + 80, 0)
  ..cubicTo((w5 + 40), 0, (w5 + 50), h5, w5 + 3, h6)
  ..lineTo(w5 - 3, h6)
  ..lineTo(w5, h)
  ..lineTo(0, h);
```

Referencia en la línea:
https://github.com/brocodev/flutter_projects/blob/main/lib/projects/travel_app/ui/feed/widgets/travel_navigation_bar.dart#L60

*Si no aplica espero tu respuesta

**Comment by brocodev** [comment]
Se ve bien bro, envia tu PR
